spring:
  application.name: gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedMethods: "*"
            allowedOriginPatterns: "*"
            allowCredentials: true
      routes:
        - id: test-service
          uri: http://localhost:8082
          predicates:
            - Path=/hello,/v3/api-docs/test-service
          filters:
            - PreserveHostHeader
            - RewritePath=/v3/api-docs/test-service,/v3/api-docs
server:
  port: 7002
